task: find_dice
global_seed: 0
vis: false
vis_graph: false
print_options: s,b,ab,r,a,o,sp,bp,abp,rp
max_steps: 20
batch_size: 20
num_skeletons: 10
flat_sample: true
flat_width: 5
pwa: 0.2
pwk: 3.0
envelope_threshold: 1
num_samples: 200
gamma: 0.98
planner: tampura_policy
learning_strategy: bayes_optimistic
decision_strategy: prob
symk_selection: unordered
symk_direction: fw
symk_simple: true
from_scratch: true
record_interval: 0.1  # seconds
